### PR TITLE
Add the new controller GUI

### PR DESCRIPTION
**Pull request by wohaopa**
image
image

### CODE REVIEW

**Comment by Dream-Master** [comment]
if we allowed to use it nice. @wohaopa did you ask the mod dev. would be more nice? I can do it as well.

**Comment by wohaopa** [comment]
> if we allowed to use it nice. @wohaopa did you ask the mod dev. would be more nice? I can do it as well.

I asked the author of the mod, and the author said there was no problem.

**Comment by Dream-Master** [comment]
@wohaopa can you copy this conversation ? or add a pic of it?

**Comment by wohaopa** [comment]
> @wohaopa can you copy this conversation ? or add a pic of it?

IMG_6111

**Comment by boubou19** [comment]
can we type the coords like before with the keyboard? i don't want to click on those chars each time i use a gate

**Comment by wohaopa** [comment]
> can we type the coords like before with the keyboard? i don't want to click on those chars each time i use a gate

You can do this. The difference from the original is that I just made the original button input easier to use.

**Review by Dream-Master — APPROVED** [review]

**Comment by wohaopa** [comment]
Hello @Dream-Master , can I add a recipe for DHD? Could you include it in version 2.7.0?

**Comment by Dream-Master** [comment]
There is a stargate pr include it there or make a pr against this branch

**Pull request merged**
