### PR TITLE
Update buildscript and general log cleanup

### PR DESCRIPTION
**Pull request by bombcar**
Migrate to new buildscript

Replace all printf uses with the logger

Remove commented out code

Remove unneeded imports

*This should be tested on a setup with working stargates!*

It builds and runs both on server and client, but I don't have an existing array to test against.

### CODE REVIEW

**Review by mitchej123 — APPROVED** [review]
tl;dr

**Comment by bombcar** [comment]
@boubou19 does Zeta have stargate networks? This should be a drop in replacement for any version of SGCraft but I’d like to verify before it goes on Delta.

**Comment by boubou19** [comment]
because it's the test server, it doesn't have a stargate network (it could have one, but after setting it 3 times already, super lazy to make a 4th)

**Comment by bombcar** [comment]
Ok so nothing should have changed at all as it was all logging and buildscript - but let’s assume it is broken - what would happen? Is it recoverable?

**Comment by boubou19** [comment]
worse thing that could happen is that the gates lose their adress so the game give new ones, messing every OC automation. But given not many players have a stargate, and not all of them know how to do proper oc interfacing, i'd say it's not that bad (except me redoing all the gates again but 🤷‍♂️ )

But if you really did what you listed then it will work

**Pull request merged**
